# ==============================
# Documentation
cerad_api01__docs:
  path: /docs
  defaults:
    _controller: cerad_api01__docs__controller:__invoke
    _template: '@CeradApi01/Docs/DocsTwigPage.twig'

# ==============================
# Project
cerad_api01__project__find_one:
  path: /project/{projectId}
  defaults:
    _controller: cerad_api01__project__find_one__controller:__invoke
    
# ==============================
# ProjectGame
cerad_api01__project_game__find_one:
  path: /project/{projectId}/game/{gameNumber}
  defaults:
    _controller: cerad_api01__project_game__find_one__controller:__invoke


   