parameters:
#    cerad_api01.example.class: Cerad\Bundle\Api01Bundle\Example

services:
#    cerad_api01.example:
#        class: %cerad_api01.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
