parameters:
  
services:

# =============================================================
# Game Stuff

  cerad_project_game__entity_manager__doctrine:
    alias: doctrine.orm.games_entity_manager
        
  cerad_project_game__game_repository__doctrine:
    class:  Cerad\Bundle\GameBundle\Doctrine\EntityRepository\GameRepository
    factory_service: 'cerad_project_game__entity_manager__doctrine'
    factory_method:  'getRepository'
    arguments:  
      - 'Cerad\Bundle\ProjectGameBundle\Doctrine\Entity\Game'
                        
  cerad_project_game__game_repository:
    alias: cerad_project_game__game_repository__doctrine
